"""
Teste
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="python_1")
def python_1_func():
    print("Teste1")

default_args={
    "owner": "Sérgio A,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2025-02-06", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Sérgio A": "mailto:sergioa64@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cm6sdbz1d1yej01mdoh8usofy/cloud-ide/cm6tunb6428ez01l04zmj24ic/cm6tuz0ju28gx01ivkmjm3rsa",
    },
)
def Teste():
    python_1 = python_1_func()

dag_obj = Teste()
